// Regenerates the launcher registries and dependencies from apps/*.
// If an app was deleted by hand, pnpm blocks scripts; run `node scripts/sync-apps.ts` directly.
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

import type { AppManifest } from "@toolkit/utils";

import { ROOT, run, APP_ID } from "./lib.ts";

type App = { id: string; pkg: string; ident: string; hasServer: boolean };

const APPS_DIR = join(ROOT, "apps");
const LAUNCHER_DIR = join(ROOT, "launcher");
const HEADER = "// Generated by scripts/sync-apps.ts from apps/*. Do not edit; run `pnpm sync`.\n";

const camelCase = (id: string) => id.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());

async function readApp(id: string): Promise<App> {
  if (!APP_ID.test(id)) throw new Error(`apps/${id}: directory name must be kebab-case`);

  const dir = join(APPS_DIR, id);
  const pkgJson = JSON.parse(readFileSync(join(dir, "package.json"), "utf8")) as {
    name: string;
    exports?: Record<string, string>;
  };
  const pkg = `@toolkit/app-${id}`;
  if (pkgJson.name !== pkg) throw new Error(`apps/${id}: package name must be "${pkg}"`);

  // Manifests only import types, so Node can load them directly.
  const manifestUrl = pathToFileURL(join(dir, "src", "manifest.ts")).href;
  const manifest = ((await import(manifestUrl)) as { default: AppManifest }).default;
  if (manifest.id !== id)
    throw new Error(`apps/${id}: manifest id "${manifest.id}" must be "${id}"`);

  return { id, pkg, ident: camelCase(id), hasServer: pkgJson.exports?.["./server"] !== undefined };
}

function uiRegistry(apps: App[]): string {
  const imports = apps.map((a) => `import ${a.ident} from "${a.pkg}/manifest";`);
  const entries = apps.map((a) => `  { manifest: ${a.ident}, load: () => import("${a.pkg}/ui") },`);
  return `${HEADER}import type { AppEntry } from "./app-entry.ts";
${imports.join("\n")}

export const apps: AppEntry[] = [
${entries.join("\n")}
];
`;
}

function serverRegistry(apps: App[]): string {
  const withServer = apps.filter((a) => a.hasServer);
  const imports = withServer.map((a) => `import ${a.ident} from "${a.pkg}/server";`);
  const entries = withServer.map((a) => `  { id: "${a.id}", app: ${a.ident} },`);
  return `${HEADER}import type { Hono } from "hono";
${imports.join("\n")}

// oxlint-disable-next-line typescript/no-explicit-any -- each app's Hono instance has its own route schema.
export const appServers: { id: string; app: Hono<any, any, any> }[] = [
${entries.join("\n")}
];
`;
}

function syncLauncherDependencies(apps: App[]): boolean {
  const file = join(LAUNCHER_DIR, "package.json");
  const before = readFileSync(file, "utf8");
  const pkg = JSON.parse(before) as { dependencies: Record<string, string> };

  const deps = Object.entries(pkg.dependencies)
    .filter(([name]) => !name.startsWith("@toolkit/app-"))
    .concat(apps.map((app) => [app.pkg, "workspace:*"]))
    .toSorted(([a], [b]) => a.localeCompare(b));
  pkg.dependencies = Object.fromEntries(deps);

  const after = `${JSON.stringify(pkg, null, 2)}\n`;
  if (after === before) return false;
  writeFileSync(file, after);
  return true;
}

export async function syncApps(): Promise<void> {
  const ids = readdirSync(APPS_DIR, { withFileTypes: true })
    .filter(
      (entry) => entry.isDirectory() && existsSync(join(APPS_DIR, entry.name, "package.json")),
    )
    .map((entry) => entry.name)
    .toSorted();
  const apps = await Promise.all(ids.map(readApp));

  const uiFile = join(LAUNCHER_DIR, "src", "registry.ts");
  const serverFile = join(LAUNCHER_DIR, "server", "registry.ts");
  writeFileSync(uiFile, uiRegistry(apps));
  writeFileSync(serverFile, serverRegistry(apps));
  const depsChanged = syncLauncherDependencies(apps);

  if (depsChanged) run("pnpm install");
  run("pnpm exec oxfmt launcher/src/registry.ts launcher/server/registry.ts launcher/package.json");

  console.log(`Synced ${apps.length} app(s): ${ids.join(", ") || "(none)"}`);
}

if (import.meta.main) await syncApps();
