// Generated by scripts/sync-apps.ts from apps/*. Do not edit; run `pnpm sync`.
import type { Hono } from "hono";

// oxlint-disable-next-line typescript/no-explicit-any -- each app's Hono instance has its own route schema.
export const appServers: { id: string; app: Hono<any, any, any> }[] = [];
