// Generated by scripts/sync-apps.ts from apps/*. Do not edit; run `pnpm sync`.
import type { AppEntry } from "./app-entry.ts";
import helloWorld from "@toolkit/app-hello-world/manifest";
import pasteboard from "@toolkit/app-pasteboard/manifest";

export const apps: AppEntry[] = [
  { manifest: helloWorld, load: () => import("@toolkit/app-hello-world/ui") },
  { manifest: pasteboard, load: () => import("@toolkit/app-pasteboard/ui") },
];
